Core:
    #Place a sign on the cenotaph if true
    cenotaphSign: true

    #Prevent non-Op players from destroying cenotaphs if true (destroyQuickLoot overrides)
    noDestroy: true

    #Save Cenotaph listing between server reloads if true
    saveCenotaphList: true

    #Stop Cenotaph creation next to existing chests if true
    noInterfere: true

    #Check for new versions on startup
    versionCheck: true

    #Cenotaph normally checks to make sure it isn't trying to create a chest in the void.
    #If you handle or modify the void with another plugin, you can disable that check here.
    #This option should be true for most servers.
    voidCheck: true

    #If you are not locking your chests with Lockette or LWC but still want them to be
    #protected against Creeper explosions, or you want your chests to be protected even
    #after they are unlocked, enable this.
    creeperProtection: false

    #If you are not locking your chests with Lockette or LWC but still want them to be
    #protected against TnT explosions, or you want your chests to be protected even
    #after they are unlocked, enable this.
    tntProtection: true

    #Each line may be one of any custom text OR:
    #{name} for player name
    #{date} for day of death
    #{time} for time of death (server time)
    #{reason} for cause of death
    #REMEMBER: LINES ARE LIMITED TO 15 CHARACTERS, AND DON'T FORGET THE QUOTES!
    Sign:
        Line1: "{name}"
        Line2: "RIP"
        Line3: "{date}"
        Line4: "{time}"

        #For formatting, see http://download.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html
        dateFormat: "MM/dd/yyyy"
        timeFormat: "hh:mm a"

    #Disable in the worlds below
    disableInWorlds:
        #- world
        #- world2

    dynmapEnable: true

Removal:
    #Destroy cenotaph on player quickloot if true
    destroyQuickLoot: true

    #Remove cenotaph after removeTime seconds if true
    cenotaphRemove: true
    removeTime: 3600

    #Set cenotaph removal time based on player level, with the above removeTime setting the maximum cap
    levelBasedRemoval: false
    levelBasedTime: 60

    #Immediately remove cenotaph once it is empty, overriding all other timeout options
    removeWhenEmpty: false

    #Never remove a cenotaph unless it is empty
    keepUntilEmpty: false

Security:
    LocketteEnable: true
    lwcEnable: false

    #Remove security after securityTimeout seconds
    securityRemove: false
    securityTimeout: 3600

    #Set LWC protection to Public instead of removing it after the timeout
    lwcPublic: false

#Remember, your character limit for the below message plus whatever else is on the line is 15 characters.
DeathMessages:
    Monster:
        Zombie: "a Zombie"
        Skeleton: "a Skeleton"
        Spider: "a Spider"
        Wolf: "a Wolf"
        Creeper: "a Creeper"
        Slime: "a Slime"
        Ghast: "a Ghast"
        PigZombie: "a Pig Zombie"
        Giant: "a Giant"
        Blaze: "a Blaze"
        CaveSpider: "a Cave Spider"
        EnderDragon: "a Dragon"
        Enderman: "an Enderman"
        IronGolem: "an Iron Golem"
        MagmaCube: "a Magma Cube"
        Silverfish: "a Siverfish"
        Other: "a Monster"
    World:
        Cactus: "a Cactus"
        Suffocation: "Suffocation"
        Fall: "a Fall"
        Fire: "a Fire"
        Burning: "Burning"
        Lava: "Lava"
        Drowning: "Drowning"
        Lightning: "Lightning"
    Explosion:
        Misc: "an Explosion"
        TNT: "a TNT Explosion"
    Misc:
        Dispenser: "a Dispenser"
        Void: "the Void"
        Other: "Unknown"

configVer: 16
